=== SouganthikaS/Time-Sectographer/XMLfiles/taskList.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT taskList (task+)>
<!ELEMENT task (name,description,date,category,status)>
<!ELEMENT name (#PCDATA) #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT status (Completed|Pending) "Pending">
<!ATTLIST task id #REQUIRED>

=== SouganthikaS/Time-Sectographer/XMLfiles/TSXML.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no" ?>
<!DOCTYPE taskList SYSTEM "taskList.dtd">
<?xml-stylesheet type="text/css" href="xmlcss.css"?> 
<taskList xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceschemaLocation="E:\TimeSectographer\taskList.xsd">
    <task id = "1">
        <name>XML Doc creation</name>
        <description>Create two XML Documents for the assignment</description>
        <date>13-11-2020</date>
        <category>Work</category>
        <status>Completed</status>
    </task>
    <task id = "2">
        <name>DTD and Schema for XML</name>
        <description>Create DTD and Schema documents for the created XML</description>
        <date>13-11-2020</date>
        <category>Work</category>
        <status>Pending</status>
    </task>
</taskList>
